version: '3.8'

services:
  # Todo Microservice
  todo-service:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=todoapp
      - DB_USER=todouser
      - DB_PASSWORD=todopass123
      - LOG_LEVEL=debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "todouser", "-ptodopass123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - todo-network
    restart: unless-stopped

  # Adminer for database management (optional)
  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  todo-network:
    driver: bridge